dist: xenial
language: python
python: 3.6
cache: pip

install:
  - pip install pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] && [[ "$TEST_CMD" == "pytest" ]]; then
      pip install pytest-cov coveralls; fi
  - if [[ $TEST_CMD == black* ]]; then pip install black; fi
  - if [[ $TEST_CMD == flake8* ]]; then pip install flake8 flake8-bugbear
      flake8-docstrings flake8-todo flake8-eradicate; fi
  - pip install -r requirements.txt

env:
- TEST_CMD="pytest"

script:
- $TEST_CMD

after_success:
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]] && [[ "$TEST_CMD" == "pytest" ]];
     then coveralls; fi

matrix:
  include:
    - name: "black"
      env:
        - TEST_CMD="black --check --verbose ."
    - name: "flake8"
      env:
        - TEST_CMD="flake8 piholeinflux.py tests/test_*.py"
    - name: "pytest-py3.5"
      python: 3.5
    - name: "pytest-py3.6"
      python: 3.6
    - name: "pytest-py3.7"
      python: 3.7
